services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=vvauijij
      - GF_SECURITY_ADMIN_PASSWORD=woe203isojb102ie
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/datasources/datasource.yml

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

volumes:
  prometheus_data: