global:
  scrape_interval: 300ms

scrape_configs:
  - job_name: 'comfyscale'
    static_configs:
      - targets: ['comfyscale:8080']
        labels:
          gpu_type: ComfyScale_T4

  - job_name: 'comfyui'
    static_configs:
      - targets: ['comfyui:8188']
        labels:
          gpu_type: ComfyUI_T4

  - job_name: 'comfyui_cpu'
    static_configs:
      - targets: ['comfyui_cpu:9100']
        labels:
          role: system_monitor
          gpu_type: ComfyUI_T4
  
  - job_name: 'comfyui_gpu'
    static_configs:
      - targets: ['comfyui_gpu:9400']
        labels:
          role: system_monitor
          gpu_type: ComfyUI_T4
