services:
  comfyscale:
    container_name: comfyscale
    image: ghcr.io/vvauijij/comfyscale:comfyscale-v0.0.4
    depends_on:
      - comfyscale_head
    environment:
      - NUM_GPUS=4
      - RAY_ADDRESS=ray://comfyscale_head:10001
    command: "python3 main.py"
    ports:
      - "8000:8188"                             # 8000: comfy app
    volumes:
      - /models:/ComfyScale/models:ro

  comfyscale_head:
    container_name: comfyscale_head
    image: ghcr.io/vvauijij/comfyscale:comfyscale-v0.0.4
    environment:
      - PYTHONPATH=/ComfyScale
    command: >
      ray start
        --head
        --port=6379
        --ray-client-server-port=10001
        --resources='{"num_parallelism": 8}' 
        --dashboard-host=0.0.0.0
        --dashboard-port=8265
        --metrics-export-port=8080
        --block
    shm_size: "8gb"
    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 24G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    ports:
      - "8001:8080"                             # 8001: comfy metrics
      - "8265:8265"                             # 8265: ray dashboard
    volumes:
      - /models:/ComfyScale/models:ro
    
  comfyscale_node1:
    container_name: comfyscale_node1
    depends_on:
      - comfyscale_head
    image: ghcr.io/vvauijij/comfyscale:comfyscale-v0.0.4
    environment:
      - PYTHONPATH=/ComfyScale
    command: >
      ray start
        --address=comfyscale_head:6379
        --metrics-export-port=8080
        --block
    shm_size: "16gb"
    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 24G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    ports:
      - "8002:8080"                               # 8002: comfy metrics
    volumes:
      - /models:/ComfyScale/models:ro

  comfyscale_node2:
    container_name: comfyscale_node2
    depends_on:
      - comfyscale_head
    image: ghcr.io/vvauijij/comfyscale:comfyscale-v0.0.4
    environment:
      - PYTHONPATH=/ComfyScale
    command: >
      ray start
        --address=comfyscale_head:6379
        --metrics-export-port=8080
        --block
    shm_size: "16gb"
    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 24G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]
    ports:
      - "8003:8080"                               # 8003: comfy metrics
    volumes:
      - /models:/ComfyScale/models:ro

  comfyscale_node3:
    container_name: comfyscale_node3
    depends_on:
      - comfyscale_head
    image: ghcr.io/vvauijij/comfyscale:comfyscale-v0.0.4
    environment:
      - PYTHONPATH=/ComfyScale
    command: >
      ray start
        --address=comfyscale_head:6379
        --metrics-export-port=8080
        --block
    shm_size: "16gb"
    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 24G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]
    ports:
      - "8004:8080"                               # 8004: comfy metrics
    volumes:
      - /models:/ComfyScale/models:ro
