services:
  comfyscale:
    container_name: comfyscale
    build:
      context: ./ComfyScale
    environment:
      - NUM_GPUS=2
      - NUM_PARALLELISM=4
    command: 'python3 main.py'
    shm_size: '32gb'
    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: '16.0'
          memory: 96G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              capabilities: [gpu]
    ports:
      - '8000:8188'                    # 8000: comfy app
      - '8001:8080'                    # 8001: comfy metrics
      - '8265:8265'                    # 8265: ray dashboard
    volumes:
      - /models:/ComfyScale/models:ro