services:
  comfyscale:
    container_name: comfyscale
    build:
      context: ./ComfyScale
    depends_on:
      - comfyscale_head
    environment:
      - NUM_GPUS=2
      - RAY_ADDRESS=ray://comfyscale_head:10001
    command: "python3 main.py"
    ports:
      - "8000:8188"                             # 8000: comfy app
    volumes:
      - /models:/ComfyScale/models:ro

  comfyscale_head:
    container_name: comfyscale_head
    build:
      context: ./ComfyScale
    environment:
      - PYTHONPATH=/ComfyScale
    command: >
      ray start
        --head
        --port=6379
        --ray-client-server-port=10001
        --resources='{"num_parallelism": 4}' 
        --dashboard-host=0.0.0.0
        --dashboard-port=8265
        --metrics-export-port=8080
        --block
    shm_size: "16gb"
    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 48G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    ports:
      - "8001:8080"                             # 8001: comfy metrics
      - "8265:8265"                             # 8265: ray dashboard
    volumes:
      - /models:/ComfyScale/models:ro
    
  comfyscale_node:
    container_name: comfyscale_node
    depends_on:
      - comfyscale_head
    build:
      context: ./ComfyScale
    environment:
      - PYTHONPATH=/ComfyScale
    command: >
      ray start
        --address=comfyscale_head:6379
        --metrics-export-port=8080
        --block
    shm_size: "16gb"
    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 48G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    ports:
      - "8002:8080"                               # 8002: comfy metrics
    volumes:
      - /models:/ComfyScale/models:ro
